# Generated by Django 2.0.2 on 2023-03-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20230320_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='has_read',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='user',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='message_content',
            field=models.CharField(max_length=200, null=True, verbose_name='消息内容'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='message_man',
            field=models.IntegerField(default=0, verbose_name='消息用户'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='message_status',
            field=models.BooleanField(default=False, verbose_name='消息状态'),
        ),
    ]
