# Generated by Django 2.0.2 on 2023-03-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20230327_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='message_man',
            new_name='user',
        ),
    ]
