# Generated by Django 2.0.2 on 2023-03-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20230327_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='message_content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='message_status',
        ),
    ]
