# Generated by Django 2.0.2 on 2023-03-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20230327_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='has_read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.CharField(max_length=500, null=True, verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.IntegerField(default=0, verbose_name='接受用户id'),
        ),
    ]
