# Generated by Django 2.0.2 on 2023-03-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_auto_20230327_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='has_read',
        ),
    ]
