# Generated by Django 2.0.2 on 2023-03-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20230315_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': '高校机构', 'verbose_name_plural': '高校机构'},
        ),
    ]
